import {
  ArrowLeft,
  ArrowRight,
  Blocks,
  Calendar,
  Check,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  CircleCheck,
  CircleMinus,
  CirclePlus,
  CircleX,
  ClipboardCheck,
  ClipboardCopy,
  Clock9,
  ExternalLink,
  Eye,
  FileX,
  GraduationCap,
  Image,
  Info,
  LayoutGrid,
  List,
  Lock,
  LogIn,
  Mail,
  Menu,
  MessageSquare,
  Minus,
  Palette,
  Pencil,
  Plus,
  Reply,
  SearchX,
  ShieldX,
  ShoppingCart,
  Smartphone,
  ThumbsUp,
  TextCursorInput,
  Ticket,
  Trash2,
  TriangleAlert,
  Type,
  UserRound,
  X,
} from "lucide-react";
import { GithubIcon } from "./custom/GithubIcon";
import { InstagramIcon } from "./custom/InstagramIcon";
import { InstagramBrandIcon } from "./custom/InstagramBrandIcon";
import { LinkedinIcon } from "./custom/LinkedinIcon";

export const registry = {
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "blocks": Blocks,
  "calendar": Calendar,
  "check": Check,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevron-down": ChevronDown,
  "circle-check": CircleCheck,
  "circle-minus": CircleMinus,
  "circle-plus": CirclePlus,
  "circle-x": CircleX,
  "clipboard-check": ClipboardCheck,
  "clipboard-copy": ClipboardCopy,
  "clock-9": Clock9,
  "external-link": ExternalLink,
  "eye": Eye,
  "file-x": FileX,
  "graduation-cap": GraduationCap,
  "image": Image,
  "info": Info,
  "layout-grid": LayoutGrid,
  "list": List,
  "lock": Lock,
  "log-in": LogIn,
  "mail": Mail,
  "menu": Menu,
  "message-square": MessageSquare,
  "minus": Minus,
  "palette": Palette,
  "pencil": Pencil,
  "plus": Plus,
  "reply": Reply,
  "search-x": SearchX,
  "shield-x": ShieldX,
  "shopping-cart": ShoppingCart,
  "smartphone": Smartphone,
  "thumbs-up": ThumbsUp,
  "text-cursor-input": TextCursorInput,
  "ticket": Ticket,
  "trash-2": Trash2,
  "triangle-alert": TriangleAlert,
  "type": Type,
  "user-round": UserRound,
  "x": X,
  "github": GithubIcon,
  "instagram": InstagramIcon,
  "instagram-brand": InstagramBrandIcon,
  "linkedin": LinkedinIcon,
} as const;

export type IconName = keyof typeof registry;

export const iconNames = Object.keys(registry) as IconName[];
