import {
  ArrowLeft,
  ArrowRight,
  ChevronRight,
  ChevronDown,
  CircleMinus,
  CirclePlus,
  Clock9,
  ExternalLink,
  Eye,
  GraduationCap,
  List,
  Lock,
  Mail,
  MessageSquare,
  Minus,
  Pencil,
  Plus,
  Reply,
  ShoppingCart,
  ThumbsUp,
  Ticket,
  Trash2,
  X,
} from "lucide-react";

export const registry = {
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "chevron-right": ChevronRight,
  "chevron-down": ChevronDown,
  "circle-minus": CircleMinus,
  "circle-plus": CirclePlus,
  "clock-9": Clock9,
  "external-link": ExternalLink,
  "eye": Eye,
  "graduation-cap": GraduationCap,
  "list": List,
  "lock": Lock,
  "mail": Mail,
  "message-square": MessageSquare,
  "minus": Minus,
  "pencil": Pencil,
  "plus": Plus,
  "reply": Reply,
  "shopping-cart": ShoppingCart,
  "thumbs-up": ThumbsUp,
  "ticket": Ticket,
  "trash-2": Trash2,
  "x": X,
  // TODO: add "github" and "linkedin" once user provides SVG paths
} as const;

export type IconName = keyof typeof registry;
